tira-io/tira

application/src/tira/checks.py
application/src/tira/data/HybridDatabase.py
application/src/tira/endpoints/data_api.py
application/src/tira/endpoints/vm_api.py
application/src/tira/grpc/grpc_server.py
application/src/tira/model.py
application/src/tira/static/tira/css/tira-style.css
application/src/tira/static/tira/js/components/leaderboard.js
application/src/tira/static/tira/js/components/reviewlist.js
application/src/tira/static/tira/js/components/runlist.js
application/src/tira/static/tira/js/software.js
application/src/tira/static/tira/js/tira-admin.js
application/src/tira/templates/tira/dataset_detail.html
application/src/tira/templates/tira/dataset_list.html
application/src/tira/templates/tira/index.html
application/src/tira/templates/tira/review.html
application/src/tira/templates/tira/software.html
application/src/tira/templates/tira/software_form.html
application/src/tira/templates/tira/task.html
application/src/tira/templates/tira/task_detail.html
application/src/tira/templates/tira/upload_form.html
application/src/tira/templates/tira/user_list.html
application/src/tira/tira_model.py
application/src/tira/urls.py
application/src/tira/views.py

@BastianGrahm: Since you mentioned some pitfalls with the file upload, could you maybe have a look at this branch and check if everything works with discourse?
Thanks!

Results file upload

---

application/src/tira/static/tira/css/tira-style.css
application/src/tira/templates/tira/base.html

This fixes #209 where labels and a radio button where displays wrong when using TIRA with Discourse.

Fix style issues in modals

---

application/src/tira/data/HybridDatabase.py
application/src/tira/endpoints/vm_api.py
application/src/tira/git_runner.py
application/src/tira/management/commands/git_runner_cli.py
application/src/tira/model.py
application/src/tira/static/tira/js/software.js
application/src/tira/templates/tira/docker_form.html
application/src/tira/templates/tira/software.html
application/src/tira/tira_model.py
application/src/tira/urls.py
application/src/tira/views.py

These are my changes to integrate the frontend part of the git-ci pipeline.
When this is merged into dev, I can continue with the backend-only stuff.
I wanted to have the basic working frontend part merged as soon as possible to keep merge conflicts at a minimum because the frontend part touches many places, for all later steps I work in isolated methods.

Integrate the frontend part of the git-ci pipeline into the development branch.

---

application/src/tira/endpoints/data_api.py
application/src/tira/frontend/src/components/participant-management/register-button.vue
application/src/tira/frontend/src/components/select-team-button.vue
application/src/tira/frontend/src/user.ts
application/src/tira/templates/tira/software.html
application/src/tira/tira_model.py
application/src/tira/views.py

This brings this to prod: https://github.com/tira-io/tira/issues/300

Switch between different groups

---

application/src/tira/git_runner_integration.py

github + gitlab runner implementation

add git_runner_integration.py

---

application/src/tira/ir_datasets_loader.py

Implements methods to export the queries as xml file to the ir_datasets_loader.py.

add: queries export to .trecxml -> ir_datasets_loader.py

---

application/src/tira/frontend-vuetify/src/TaskOverview.vue

Added expandable details section to table
Added sorting functionality
Added Buttons to show results, SERP and run

Issue #428

---

application/src/tira/frontend-vuetify/src/Home.vue

added class to overwrite discourse default link behaviour

fixed link color on HomePage

---

application/src/tira/frontend-vuetify/src/submission-components/RunningProcesses.vue

#487 running processes should be collapsed by default

---

application/src/tira/frontend-vuetify/src/__tests__/data-filter-test.ts
application/src/tira/frontend-vuetify/src/components/index.ts
application/src/tira/frontend-vuetify/src/submission-components/DockerSubmission.vue
application/src/tira/frontend-vuetify/src/submission-components/ExistingDockerSubmission.vue
application/src/tira/frontend-vuetify/src/submission-components/NewDockerSubmission.vue
application/src/tira/frontend-vuetify/src/submission-components/UploadSubmission.vue
application/src/tira/frontend-vuetify/src/utils.ts

#484 finalize vueitfy upload submissions

---

application/src/tira/frontend-vuetify/src/submission-components/RunningProcesses.vue

Added API-call for stopping running process

Added REST-call for cancelling a running process.

---

application/Dockerfile.application
application/Makefile
application/src/tira/frontend-vuetify/package.json
application/src/tira/frontend-vuetify/src/TaskOverview.vue
application/src/tira/frontend-vuetify/src/components/CodeSnippet.vue
application/src/tira/frontend-vuetify/src/components/EditDataset.vue
application/src/tira/frontend-vuetify/src/components/RunReviewWindow.vue
application/src/tira/frontend-vuetify/src/main.ts
application/src/tira/frontend-vuetify/src/submission-components/ExistingDockerSubmission.vue
application/src/tira/frontend-vuetify/src/submission-components/RunningProcesses.vue
application/src/tira/frontend-vuetify/src/submission-components/UploadSubmission.vue
application/src/tira/frontend-vuetify/src/utils.ts

Deleted console.log statements in different files, since the browser console became quite cluttered with logged information, which was most likely remains of past testing
Added v-if to card in RunningProcesses.vue, so there is no empty card displayed when there are no runs
Changed error handling function in utils.ts, so it does not print [object Object] to screen when there is no error in success message.
Added "vite-build-light" command to package.json and Makefile which runs without testing. This is useful for development which does not target any programming logic.

#535 directly show the details on how to upload docker images to tira

---

application/src/tirex-components.yml

Changed name of component.

---

application/src/tirex-components.yml

@mam10eks Here are the additions of links to TIREx retrieval approaches (all were re-ranking, right?)
I've also fixed the YAML format.

Add TIREx approaches

---

application/src/tira/frontend-vuetify/src/IrComponents.vue
application/src/tira/frontend-vuetify/src/__tests__/url-extraction-test.ts
application/src/tira/frontend-vuetify/src/utils.ts

fixed tests
reset formating on imports in IrComponents.vue

fixed tests

---

application/src/tira/frontend-vuetify/src/IrComponents.vue

Expanding components based on url and search query now works on desktop view swell

#522 easy browsing/searching of al public components

---

application/src/tira/frontend-vuetify/src/Tasks.vue
application/src/tira/frontend-vuetify/src/components/OverviewMissingReviews.vue
application/src/tira/frontend-vuetify/src/components/RunList.vue

Vite now compiles without errors. Fixed value access according to breaking changes in vuetify version 3.3.18
https://github.com/vuetifyjs/vuetify/releases/tag/v3.3.18

#593 type errors when compiling, most likely due to vuetify version change

---

application/src/tira/frontend-vuetify/src/RunUpload.vue
application/src/tira/frontend-vuetify/src/submission-components/DockerSubmission.vue
application/src/tira/frontend-vuetify/src/submission-components/NewDockerSubmission.vue

Implemented Vuetify Stepper component

#589 change custom stepper to vuetify stepper

---

python-client/sphinx/unlisted/maintenance.rst

Hi, I just added a heading and slightly different text with a link to the TIRA contact page.

added description and contact link to maintenance file.

---

python-client/tira/pyterrier_integration.py
python-client/tira/pyterrier_util.py

This PR reduces code duplication between `tira.pt.doc_features()` and `tira.pt.query_features()`, and makes it easier to add new query-only, doc-only or query-document features.
The new `TiraApplyFeatureTransformer` accepts a `mapping` parameter that assigns input rows to a feature or feature vector. For instance, if we have a mapping with `mapping['q0']['doc0'] = np.array([.1, .2])`, we can instantiate the transformer as `TiraApplyFeatureTransformer(mapping, ('qid', 'docno'))`. For one row, it will then create the features by selecting `mapping[row['qid']][row['docno']]`.
@mam10eks if that's alright with you, I will expand the `doc_features` and `query_features` unit tests later, after the LongEval deadline. Do I also need to update or add documentation somewhere?

Move feature transformer to pyterrier_util
